name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  secret-generator:
    runs-on: ubuntu-latest
    steps:
    - name: generate secret
      shell: bash
      run: |
        GENERATED_SECRET=$((RANDOM))
        echo "handle=$GENERATED_SECRET" >> "$GITHUB_OUTPUT"
  secret-consumer:
    runs-on: macos-latest
    needs: secret-generator
    steps:
    - name: use secret
      shell: bash
      run: |
        SECRET_HANDLE="${{ needs.secret-generator.outputs.handle }}"
        echo "We retrieved our masked secret: $SECRET_HANDLE"
