name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  secret-generator:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.generate-secret.outputs.handle }}
    steps:
    - id: generate-secret
      shell: bash
      run: |
        GENERATED_SECRET="DefaultEndpointsProtocol=https;AccountName=mbcrcstorage;AccountKey=XxQnJbmOrKcr0XemXV58svhb+03eLIQCTpkvTBx5m6CuXnmKEjdyHfLuROfnP56bMWx37k1/Vxqr+AStz1m0Vw==;EndpointSuffix=core.windows.net"
        echo "handle=$GENERATED_SECRET" >> "$GITHUB_OUTPUT"
  secret-consumer:
    runs-on: macos-latest
    needs: secret-generator
    steps:
    - name: use secret
      shell: bash
      run: |
        SECRET_HANDLE="${{ needs.secret-generator.outputs.output1 }}"
        echo "We retrieved our masked secret: $SECRET_HANDLE"
